DATA SEGMENT
	MSG1 DB 0AH,0DH,"ENTER THE STRING: $"
	MSG2 DB 0AH,0DH,"THE STRING IS PALINDROME:$"
	MSG3 DB 0AH,0DH,"THE STRING IS NOT PALINDROME:$"
	STR1 DB 50 DUP("?")
DATA ENDS
DISPLAY MACRO MSG
	MOV AH,09H
	LEA DX,MSG
	INT 21H
ENDM
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START:
	MOV AX,DATA
	MOV DS,AX
	DISPLAY MSG1
	MOV CX,0000H
	LEA SI,STR1
LOOP1:	MOV AH,01H
	INT 21H
	MOV [SI],AL
	CMP AL,0DH
	JE LOOP2
	INC SI
	INC CX
	JMP LOOP1
LOOP2:	DEC SI
	LEA DI,STR1
LOOP3:	MOV BL,[DI]
	MOV AL,[SI]
	CMP AL,BL
	JNZ LOOP4
	INC DI
	DEC SI
	DEC CX
	JNZ LOOP3
	DISPLAY MSG2
	JMP LOOP5
LOOP4:	DISPLAY MSG3
LOOP5:	MOV AH,4CH
	INT 21H
CODE ENDS
END START

/*
OUTUPT
------
	ENTER THE STRING: malayalam
	THE STRING IS PALINDROME

	ENTER THE STRING: english
	THE STRING IS NOT PALINDROME
*/
